baseurl = "/espm-157"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "ESPM 157"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Carl Boettiger"
  bio = ""
  job = "Assistant Professor"
  location = "UC Berkeley"
  gravatarEmail = "cboettig@gmail.com"
  # Your profile picture
#  picture = ""
  twitter = "cboettig"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "modules"
  name = "Modules"
  pre = "<i class=\"material-icons\">dashboard</i>"
  url = "/modules"  
[[menu.main]]
  weight = 3
  identifier = "tools"
  name = "Tools"
  pre = "<i class=\"material-icons\">build</i>"
  url = "/tools"
[[menu.main]]
  weight = 4
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 5
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"

[[menu.footer]]
  weight = 1
  identifier = "Berkeley"
  name = "UC Berkeley"
  pre = "<i class=\"material-icons\">pin_drop</i>"
  url = "https://data.berkeley.edu"
[[menu.footer]]
  weight = 2
  identifier = "GitHub"
  name = "Team Repos"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/espm-157"
[[menu.footer]]
  weight = 3
  identifier = "Piazza"
  name = "Forum"
  pre = "<i class=\"material-icons\">forum</i>"
  url = "https://piazza.com/berkeley/fall2017/espm157/home"
#[[menu.footer]]
#  weight = 4
#  name = "get R"
#  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
#  url = "https://r-project.org"

[params]
  dateFormat = "January 2, 2006"
  background = "https://climate.nasa.gov/system/internal_resources/details/original/417_1263_banner-science-1600x500.jpg"
  math = "true"

